# Generated by Django 5.0.6 on 2024-05-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_crud'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='age',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='crud',
            name='designation',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
